### ISSUE TITLE
Not working on kernel 4.14

### ISSUE THREAD

**Issue by MazenElzanaty** [abhijeet2096/TL-WN722N-V2#9]
iwconfig wlan1 mode monitor 
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan1 ; Invalid argument.

**Comment by abhijeet2096** [comment]
I will surely try to work that out in the coming week.

**Comment by vamilson** [comment]
Failed start monitor mode in kernel 4.14.0 :(
lsusb:
Bus 002 Device 006: ID 2357:010c

airmon-ng:
PHY	Interface	Driver		Chipset
null	wlan0		r8188eu		 

iwconfig wlan0 mode monitor:
Error for wireless request "Set Mode" (8B06) :
SET failed on device wlan0 ; Invalid argument.

**Comment by abhijeet2096** [comment]
Hey,

I will port this to kernel 4.14 soon ,

Thanks
Abhijeet

**Comment by vamilson** [comment]
Thanks. \o/

**Comment by abhijeet2096** [comment]
Hey vamilson , check now it should work now . Don't forgot to install "linux-headers" as per New Readme !

**Comment by vamilson** [comment]
Thanks for the update Abhijeet, but I still have problems with the installation of the drive...
I am using Kali 2018.1.
$uname -r
4.14.0-kali3-amd64

The commands executed are down below:
$ sudo apt-get update
...

$ sudo apt-get upgrade
...

$ sudo apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gconf-service gconf2-common libgconf-2-4 libgcr-3-common libjs-excanvas vino
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  linux-headers-4.14.0-kali3-common
The following NEW packages will be installed:
  linux-headers-4.14.0-kali3-amd64 linux-headers-4.14.0-kali3-common
0 upgraded, 2 newly installed, 0 to remove and 57 not upgraded.
Need to get 8.320 kB of archives.
After this operation, 51,9 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://kali.mirror.globo.tech/kali kali-rolling/main amd64 linux-headers-4.14.0-kali3-common all 4.14.17-1kali1 [7.855 kB]
Get:2 http://kali.mirror.globo.tech/kali kali-rolling/main amd64 linux-headers-4.14.0-kali3-amd64 amd64 4.14.17-1kali1 [466 kB]
Fetched 8.320 kB in 9s (883 kB/s)                                              
Selecting previously unselected package linux-headers-4.14.0-kali3-common.
(Reading database ... 337407 files and directories currently installed.)
Preparing to unpack .../linux-headers-4.14.0-kali3-common_4.14.17-1kali1_all.deb ...
Unpacking linux-headers-4.14.0-kali3-common (4.14.17-1kali1) ...
Selecting previously unselected package linux-headers-4.14.0-kali3-amd64.
Preparing to unpack .../linux-headers-4.14.0-kali3-amd64_4.14.17-1kali1_amd64.deb ...
Unpacking linux-headers-4.14.0-kali3-amd64 (4.14.17-1kali1) ...
Setting up linux-headers-4.14.0-kali3-common (4.14.17-1kali1) ...
Setting up linux-headers-4.14.0-kali3-amd64 (4.14.17-1kali1) ...

$ sudo apt-get install git dkms git make build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4).
dkms is already the newest version (2.3-3).
git is already the newest version (1:2.16.2-1).
make is already the newest version (4.1-9.1).
The following packages were automatically installed and are no longer required:
  gconf-service gconf2-common libgconf-2-4 libgcr-3-common libjs-excanvas vino
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.

$ cd /usr/src/
After Download...
$ ls
linux-headers-4.14.0-kali3-amd64   linux-kbuild-4.14  volatility-tools
linux-headers-4.14.0-kali3-common  **TL-WN722N-V2**

$ sudo dkms add ./TL-WN722N-V2
Creating symlink /var/lib/dkms/8188eu/1.2/source ->
                 /usr/src/8188eu-1.2
DKMS: add completed.

$ sudo dkms build -m 8188eu -v 1.2
Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
cleaning build area...
'make' all..........................
cleaning build area.....
DKMS: build completed.

$ sudo dkms install -m 8188eu -v 1.2
8188eu:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.14.0-kali3-amd64/kernel/drivers/net/wireless//
depmod...
Backing up initrd.img-4.14.0-kali3-amd64 to /boot/initrd.img-4.14.0-kali3-amd64.old-dkms
Making new initrd.img-4.14.0-kali3-amd64
(If next boot fails, revert to initrd.img-4.14.0-kali3-amd64.old-dkms image)
update-initramfs...
DKMS: install completed.

## The Problem:   :'(
$ sudo modprobe 8188eu 
modprobe: ERROR: could not insert '8188eu': Unknown symbol in module, or unknown parameter (see dmesg)

## Testing monitor mode:
$ sudo iwconfig wlan0 mode monitor 
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.

I don't know what to do anymore.
I need your help, please!
